# Generated by Django 3.2.8 on 2022-11-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_subcategories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='searched',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
