# Generated by Django 3.2.8 on 2022-11-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_searched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
