# Generated by Django 3.2.8 on 2022-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20221130_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_sell',
            field=models.IntegerField(default=0),
        ),
    ]
